# -*- coding: utf-8 -*-
"""翻译模块：markdown 占位保护与腾讯云 TC3 签名等自包含逻辑。

从 main.py 抽出，便于独立维护与测试。只依赖标准库，不依赖应用主模块。
"""

import datetime as _datetime
import hashlib as _hashlib
import hmac as _hmac
import json as _json
import re as _re
import time as _time

# ---------------------------------------------------------------------------
# Markdown 占位保护层
# 翻译前把代码块、HTML、URL 等替换为不可翻译占位符，翻译后原样恢复，
# 避免第三方翻译接口破坏格式、翻译代码或丢失链接。
# ---------------------------------------------------------------------------

# 当前占位符（3 位字母序号，实测腾讯翻译不会拆分纯字母串）
PLACEHOLDER_RESIDUAL = _re.compile(r"ZXQPH[A-Z]{3}TK")

# 旧版字节码内部占位符（ZXQGOSB{n}TOKEN）被腾讯拆成带空格后恢复失败而残留
LEGACY_PLACEHOLDER_RESIDUAL = _re.compile(r"ZXQGOSB\s*\d+\s*TOKEN")


def placeholder_token(index: int) -> str:
    """生成 3 位字母序号占位符（ZXQPHAAATK…），纯字母格式避免翻译接口
    按"词+数字+词"分词拆分（实测 ZXQPH0TK 会被腾讯拆成 ZXQPH 0 TK）。"""
    n = index
    chars = []
    for _ in range(3):
        chars.append(chr(ord("A") + n % 26))
        n //= 26
    return "ZXQPH" + "".join(reversed(chars)) + "TK"


def protect_markdown_blocks(markdown_text) -> tuple[str, list[str]]:
    """把代码块、HTML 标签、RST 指令、表格分隔线、行内代码与 URL 替换为
    占位符（ZXQPHAAATK 形式），返回（保护后文本, 原文映射列表）。"""
    mappings: list[str] = []

    def _replace(match) -> str:
        token = placeholder_token(len(mappings))
        mappings.append(match.group(0))
        return token

    text = str(markdown_text or "")
    patterns = (
        # 围栏代码块（含语言标签，可跨行）
        _re.compile(r"```.*?```", _re.S),
        # 行内代码（先于 HTML，避免反引号内的 <tag> 被 HTML 规则抢先替换造成嵌套）
        _re.compile(r"`[^`\n]+`"),
        # HTML 注释与标签（含属性）
        _re.compile(r"<(?:!--.*?-->|/?[a-zA-Z][^>]*)>", _re.S),
        # reStructuredText 指令及其选项行（.. image:: 等）
        _re.compile(r"(?m)^\s*\.\.\s+[a-zA-Z_-]+::[^\n]*(?:\n\s*:[a-zA-Z_-]+:\s*[^\n]*)*"),
        # Markdown 表格分隔行（| --- | --- |）
        _re.compile(r"(?m)^\s*\|?[\s:|-]*-{3,}[\s:|-]*\|[\s:|-]*(?:-{3,}[\s:|-]*\|?)+\s*$"),
        # URL（含协议）
        _re.compile(r"https?://[^\s<>\"')\]]+"),
    )
    for pattern in patterns:
        text = pattern.sub(_replace, text)
    return text, mappings


def restore_markdown_blocks(translated_text: str, mappings: list[str]) -> str:
    result = str(translated_text or "")
    for index, original in enumerate(mappings):
        result = result.replace(placeholder_token(index), original)
    return result


def protect_markdown_fragment_noop(text, state) -> str:
    """关闭旧版字节码内部 ZXQGOSB 占位保护（已被外层保护层取代）。"""
    return str(text or "")


# ---------------------------------------------------------------------------
# 术语表保护
# 翻译前保护技术术语（API、Repository 等），避免被翻译接口翻译成中文。
# ---------------------------------------------------------------------------

# 常见技术术语表（大小写不敏感匹配，输出时保持原文大小写）
GLOSSARY_TERMS = [
    # Git/GitHub 相关
    "API", "CLI", "SDK", "REST", "GraphQL", "OAuth", "SSH", "HTTPS", "HTTP",
    "Repository", "Pull Request", "Issue", "Fork", "Star", "Gist",
    "Branch", "Commit", "Merge", "Rebase", "Clone", "Push", "Pull",
    "README", "LICENSE", "CHANGELOG", "TODO", "FIXME", "HACK",
    # 编程语言/框架
    "Python", "JavaScript", "TypeScript", "Rust", "Go", "Java", "C++", "C#",
    "React", "Vue", "Angular", "Node.js", "Django", "Flask", "FastAPI",
    "PyQt", "Tkinter", "Electron", "Tauri",
    # 工具/服务
    "Docker", "Kubernetes", "K8s", "Terraform", "Ansible", "Jenkins",
    "GitHub Actions", "GitLab CI", "Travis CI", "CircleCI",
    "npm", "pip", "cargo", "yarn", "pnpm", "bun",
    "VSCode", "IntelliJ", "Vim", "Neovim", "Emacs",
    # 数据格式/协议
    "JSON", "YAML", "TOML", "XML", "CSV", "Markdown", "HTML", "CSS",
    "WebSocket", "gRPC", "TCP", "UDP", "DNS", "CDN",
    # 概念/术语
    "Open Source", "MIT License", "Apache License", "GPL",
    "Frontend", "Backend", "Full Stack", "DevOps", "MLOps",
    "Machine Learning", "Deep Learning", "Neural Network",
    "CI/CD", "CDN", "WASM", "WebAssembly",
    # 品牌/产品
    "GitHub", "GitLab", "Bitbucket", "Jira", "Confluence",
    "AWS", "Azure", "GCP", "Google Cloud", "Cloudflare",
    "Vercel", "Netlify", "Heroku", "Railway",
]

# 预编译术语正则（大小写不敏感，匹配完整单词）
_GLOSSARY_PATTERN = _re.compile(
    r'\b(' + '|'.join(_re.escape(t) for t in GLOSSARY_TERMS) + r')\b',
    _re.IGNORECASE
)


def protect_glossary_terms(text: str) -> tuple[str, list[tuple[str, str]]]:
    """翻译前保护术语表中的技术术语，返回（保护后文本, 术语映射列表）。

    每个映射为 (占位符, 原文)，翻译后调用 restore_glossary_terms() 恢复。
    """
    mappings: list[tuple[str, str]] = []

    def _replace(match) -> str:
        original = match.group(0)
        token = placeholder_token(len(mappings) + 1000)  # 偏移 1000 避免与 block 占位符冲突
        mappings.append((token, original))
        return token

    protected = _GLOSSARY_PATTERN.sub(_replace, str(text or ""))
    return protected, mappings


def restore_glossary_terms(translated_text: str, mappings: list[tuple[str, str]]) -> str:
    """翻译后恢复术语表中的技术术语。"""
    result = str(translated_text or "")
    for token, original in mappings:
        result = result.replace(token, original)
    return result


# ---------------------------------------------------------------------------
# 本地翻译词典
# 用于离线翻译 GitHub 项目描述和 README，覆盖常见技术术语和界面用语。
# ---------------------------------------------------------------------------

# 英 -> 中 本地翻译词典（小写键，匹配时忽略大小写）
LOCAL_TRANSLATION_DICT = {
    # Git/GitHub 核心概念
    "repository": "仓库",
    "repo": "仓库",
    "fork": "复刻",
    "star": "星标",
    "stargazer": "星标者",
    "clone": "克隆",
    "commit": "提交",
    "branch": "分支",
    "merge": "合并",
    "rebase": "变基",
    "pull request": "拉取请求",
    "pull": "拉取",
    "push": "推送",
    "issue": "议题",
    "gist": "代码片段",
    "tag": "标签",
    "release": "发行版",
    "version": "版本",
    "changelog": "更新日志",
    "readme": "说明文档",
    "license": "许可证",
    "contributing": "贡献指南",
    "code of conduct": "行为准则",
    "security": "安全",
    "wiki": "维基",
    "discussion": "讨论",
    "project": "项目",
    "organization": "组织",
    "team": "团队",
    "member": "成员",
    "collaborator": "协作者",
    "contributor": "贡献者",
    "maintainer": "维护者",
    "owner": "所有者",
    "admin": "管理员",
    "public": "公开",
    "private": "私有",
    "template": "模板",
    "default": "默认",
    "main": "主分支",
    "master": "主分支",
    "head": "头指针",
    "origin": "远程源",
    "upstream": "上游",
    "remote": "远程",
    "local": "本地",
    "workspace": "工作区",
    "staging": "暂存",
    "index": "索引",
    "working tree": "工作树",
    "detached head": "分离头指针",
    "conflict": "冲突",
    "resolve": "解决",
    "rollback": "回滚",
    "revert": "还原",
    "reset": "重置",
    "checkout": "检出",
    "stash": "储藏",
    "diff": "差异",
    "log": "日志",
    "blame": "追溯",
    "bisect": "二分查找",
    "submodule": "子模块",
    "subtree": "子树",
    "hook": "钩子",
    "webhook": "网络钩子",
    "action": "操作",
    "workflow": "工作流",
    "pipeline": "流水线",
    "job": "任务",
    "step": "步骤",
    "runner": "运行器",
    "artifact": "产物",
    "cache": "缓存",
    "secret": "密钥",
    "variable": "变量",
    "environment": "环境",
    "deployment": "部署",
    "deploy": "部署",
    "rollback": "回滚",
    "status": "状态",
    "check": "检查",
    "review": "审查",
    "approve": "批准",
    "request changes": "请求更改",
    "comment": "评论",
    "thread": "线程",
    "mention": "提及",
    "assign": "指派",
    "label": "标签",
    "milestone": "里程碑",
    "board": "看板",
    "card": "卡片",
    "column": "列",
    "automation": "自动化",
    "bot": "机器人",
    "integration": "集成",
    "plugin": "插件",
    "extension": "扩展",
    "app": "应用",
    "marketplace": "应用市场",
    "api": "应用程序接口",
    "sdk": "软件开发工具包",
    "cli": "命令行界面",
    "gui": "图形界面",
    "ui": "用户界面",
    "ux": "用户体验",
    "endpoint": "端点",
    "token": "令牌",
    "authentication": "身份验证",
    "authorization": "授权",
    "permission": "权限",
    "access": "访问",
    "scope": "作用域",
    "rate limit": "速率限制",
    "quota": "配额",
    "callback": "回调",
    "redirect": "重定向",
    "oauth": "开放授权",
    "jwt": "JSON网络令牌",
    "cors": "跨域资源共享",
    "ssl": "安全套接层",
    "tls": "传输层安全",
    "https": "超文本传输安全协议",
    "http": "超文本传输协议",
    "dns": "域名系统",
    "cdn": "内容分发网络",
    "proxy": "代理",
    "mirror": "镜像",
    "backup": "备份",
    "sync": "同步",
    "async": "异步",
    "concurrent": "并发",
    "parallel": "并行",
    "thread": "线程",
    "process": "进程",
    "daemon": "守护进程",
    "service": "服务",
    "server": "服务器",
    "client": "客户端",
    "database": "数据库",
    "cache": "缓存",
    "queue": "队列",
    "stack": "栈",
    "heap": "堆",
    "array": "数组",
    "list": "列表",
    "map": "映射",
    "set": "集合",
    "tree": "树",
    "graph": "图",
    "hash": "哈希",
    "sort": "排序",
    "search": "搜索",
    "filter": "过滤",
    "reduce": "归并",
    "iterate": "迭代",
    "recursion": "递归",
    "loop": "循环",
    "condition": "条件",
    "exception": "异常",
    "error": "错误",
    "bug": "缺陷",
    "debug": "调试",
    "test": "测试",
    "unit test": "单元测试",
    "integration test": "集成测试",
    "end to end test": "端到端测试",
    "mock": "模拟",
    "stub": "桩",
    "assertion": "断言",
    "coverage": "覆盖率",
    "lint": "代码检查",
    "format": "格式化",
    "refactor": "重构",
    "optimize": "优化",
    "performance": "性能",
    "benchmark": "基准测试",
    "profile": "分析",
    "memory": "内存",
    "cpu": "处理器",
    "gpu": "图形处理器",
    "io": "输入输出",
    "network": "网络",
    "disk": "磁盘",
    "file": "文件",
    "folder": "文件夹",
    "directory": "目录",
    "path": "路径",
    "url": "网址",
    "link": "链接",
    "image": "图片",
    "video": "视频",
    "audio": "音频",
    "document": "文档",
    "data": "数据",
    "json": "JSON数据",
    "xml": "XML数据",
    "csv": "CSV数据",
    "yaml": "YAML数据",
    "toml": "TOML数据",
    "markdown": "Markdown文档",
    "html": "HTML文档",
    "css": "CSS样式",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "python": "Python",
    "java": "Java",
    "go": "Go",
    "rust": "Rust",
    "c": "C语言",
    "cpp": "C++",
    "csharp": "C#",
    "ruby": "Ruby",
    "php": "PHP",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "scala": "Scala",
    "r": "R语言",
    "matlab": "MATLAB",
    "sql": "SQL",
    "nosql": "NoSQL",
    "react": "React",
    "vue": "Vue",
    "angular": "Angular",
    "svelte": "Svelte",
    "next": "Next.js",
    "nuxt": "Nuxt.js",
    "express": "Express",
    "fastify": "Fastify",
    "django": "Django",
    "flask": "Flask",
    "fastapi": "FastAPI",
    "spring": "Spring",
    "laravel": "Laravel",
    "rails": "Rails",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "K8s",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "jenkins": "Jenkins",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",
    "jira": "Jira",
    "confluence": "Confluence",
    "slack": "Slack",
    "discord": "Discord",
    "aws": "亚马逊云",
    "azure": "微软云",
    "gcp": "谷歌云",
    "cloudflare": "Cloudflare",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "heroku": "Heroku",
    "digitalocean": "DigitalOcean",
    "linux": "Linux",
    "windows": "Windows",
    "macos": "macOS",
    "android": "安卓",
    "ios": "iOS",
    "frontend": "前端",
    "backend": "后端",
    "fullstack": "全栈",
    "devops": "运维",
    "mlops": "机器学习运维",
    "sre": "站点可靠性工程",
    "cloud": "云",
    "serverless": "无服务器",
    "microservice": "微服务",
    "monolith": "单体应用",
    "container": "容器",
    "image": "镜像",
    "volume": "卷",
    "network": "网络",
    "load balancer": "负载均衡",
    "reverse proxy": "反向代理",
    "api gateway": "API网关",
    "message queue": "消息队列",
    "event driven": "事件驱动",
    "pub sub": "发布订阅",
    "websocket": "WebSocket",
    "grpc": "gRPC",
    "rest": "REST",
    "graphql": "GraphQL",
    "soap": "SOAP",
    "microservice": "微服务",
    "architecture": "架构",
    "design pattern": "设计模式",
    "solid": "SOLID原则",
    "dry": "不要重复自己",
    "kiss": "保持简单",
    "yagni": "你不会需要它",
    "agile": "敏捷",
    "scrum": "Scrum",
    "kanban": "看板",
    "sprint": "冲刺",
    "backlog": "待办列表",
    "epic": "史诗",
    "story": "用户故事",
    "task": "任务",
    "feature": "功能",
    "enhancement": "增强",
    "hotfix": "热修复",
    "patch": "补丁",
    "update": "更新",
    "upgrade": "升级",
    "downgrade": "降级",
    "install": "安装",
    "uninstall": "卸载",
    "setup": "设置",
    "configure": "配置",
    "initialize": "初始化",
    "create": "创建",
    "delete": "删除",
    "remove": "移除",
    "add": "添加",
    "update": "更新",
    "modify": "修改",
    "edit": "编辑",
    "save": "保存",
    "load": "加载",
    "import": "导入",
    "export": "导出",
    "upload": "上传",
    "download": "下载",
    "fetch": "获取",
    "send": "发送",
    "receive": "接收",
    "request": "请求",
    "response": "响应",
    "parse": "解析",
    "serialize": "序列化",
    "deserialize": "反序列化",
    "encode": "编码",
    "decode": "解码",
    "encrypt": "加密",
    "decrypt": "解密",
    "hash": "哈希",
    "sign": "签名",
    "verify": "验证",
    "validate": "验证",
    "sanitize": "清理",
    "escape": "转义",
    "normalize": "标准化",
    "convert": "转换",
    "transform": "转换",
    "map": "映射",
    "filter": "过滤",
    "reduce": "归并",
    "aggregate": "聚合",
    "group": "分组",
    "join": "连接",
    "merge": "合并",
    "split": "分割",
    "concat": "连接",
    "compare": "比较",
    "match": "匹配",
    "replace": "替换",
    "find": "查找",
    "search": "搜索",
    "index": "索引",
    "query": "查询",
    "scan": "扫描",
    "traverse": "遍历",
    "iterate": "迭代",
    "loop": "循环",
    "recurse": "递归",
    "backtrack": "回溯",
    "dynamic programming": "动态规划",
    "greedy": "贪心",
    "divide and conquer": "分治",
    "brute force": "暴力搜索",
    "binary search": "二分查找",
    "linear search": "线性查找",
    "depth first": "深度优先",
    "breadth first": "广度优先",
    "dijkstra": "迪杰斯特拉",
    "bellman ford": "贝尔曼-福特",
    "floyd": "弗洛伊德",
    "kruskal": "克鲁斯卡尔",
    "prim": "普里姆",
    "tree": "树",
    "binary tree": "二叉树",
    "avl tree": "AVL树",
    "red black tree": "红黑树",
    "b tree": "B树",
    "trie": "字典树",
    "heap": "堆",
    "priority queue": "优先队列",
    "stack": "栈",
    "queue": "队列",
    "deque": "双端队列",
    "linked list": "链表",
    "doubly linked list": "双向链表",
    "circular list": "循环链表",
    "hash table": "哈希表",
    "hash map": "哈希映射",
    "hash set": "哈希集合",
    "array": "数组",
    "matrix": "矩阵",
    "vector": "向量",
    "tensor": "张量",
    "graph": "图",
    "directed graph": "有向图",
    "undirected graph": "无向图",
    "weighted graph": "加权图",
    "adjacency matrix": "邻接矩阵",
    "adjacency list": "邻接表",
    "edge": "边",
    "vertex": "顶点",
    "node": "节点",
    "leaf": "叶子",
    "root": "根",
    "parent": "父节点",
    "child": "子节点",
    "sibling": "兄弟节点",
    "ancestor": "祖先",
    "descendant": "后代",
    "depth": "深度",
    "height": "高度",
    "size": "大小",
    "length": "长度",
    "width": "宽度",
    "capacity": "容量",
    "count": "计数",
    "frequency": "频率",
    "occurrence": "出现",
    "duplicate": "重复",
    "unique": "唯一",
    "distinct": "不同",
    "common": "公共",
    "shared": "共享",
    "private": "私有",
    "public": "公开",
    "protected": "受保护",
    "internal": "内部",
    "external": "外部",
    "local": "局部",
    "global": "全局",
    "static": "静态",
    "dynamic": "动态",
    "constant": "常量",
    "variable": "变量",
    "parameter": "参数",
    "argument": "实参",
    "return": "返回",
    "yield": "产出",
    "throw": "抛出",
    "catch": "捕获",
    "finally": "最终",
    "try": "尝试",
    "except": "异常",
    "raise": "引发",
    "assert": "断言",
    "guard": "守卫",
    "precondition": "前置条件",
    "postcondition": "后置条件",
    "invariant": "不变量",
    "side effect": "副作用",
    "pure function": "纯函数",
    "higher order": "高阶",
    "callback": "回调",
    "closure": "闭包",
    "lambda": "匿名函数",
    "anonymous": "匿名",
    "delegate": "委托",
    "event": "事件",
    "listener": "监听器",
    "handler": "处理器",
    "observer": "观察者",
    "subscriber": "订阅者",
    "publisher": "发布者",
    "emitter": "发射器",
    "dispatcher": "调度器",
    "scheduler": "调度器",
    "timer": "定时器",
    "interval": "间隔",
    "timeout": "超时",
    "delay": "延迟",
    "async": "异步",
    "await": "等待",
    "promise": "承诺",
    "future": "未来值",
    "observable": "可观察",
    "stream": "流",
    "buffer": "缓冲区",
    "channel": "通道",
    "pipe": "管道",
    "socket": "套接字",
    "port": "端口",
    "host": "主机",
    "domain": "域名",
    "subdomain": "子域名",
    "tld": "顶级域名",
    "protocol": "协议",
    "scheme": "方案",
    "request": "请求",
    "response": "响应",
    "header": "头部",
    "body": "正文",
    "payload": "负载",
    "content": "内容",
    "type": "类型",
    "mime": "MIME类型",
    "charset": "字符集",
    "encoding": "编码",
    "compression": "压缩",
    "decompression": "解压缩",
    "zip": "压缩",
    "unzip": "解压缩",
    "tar": "归档",
    "gzip": "gzip压缩",
    "bzip": "bzip压缩",
    "xz": "xz压缩",
    "lzma": "lzma压缩",
    "zstd": "zstd压缩",
    "snappy": "snappy压缩",
    "lz4": "lz4压缩",
    "brotli": "brotli压缩",
    "deflate": "deflate压缩",
    "inflate": "inflate解压缩",
    "checksum": "校验和",
    "crc": "循环冗余校验",
    "md5": "MD5",
    "sha": "SHA",
    "sha1": "SHA1",
    "sha256": "SHA256",
    "sha512": "SHA512",
    "hmac": "HMAC",
    "aes": "AES",
    "rsa": "RSA",
    "dsa": "DSA",
    "ecdsa": "ECDSA",
    "ed25519": "Ed25519",
    "certificate": "证书",
    "key": "密钥",
    "public key": "公钥",
    "private key": "私钥",
    "keystore": "密钥库",
    "truststore": "信任库",
    "ca": "证书颁发机构",
    "csr": "证书签名请求",
    "pem": "PEM格式",
    "der": "DER格式",
    "p12": "P12格式",
    "jks": "JKS格式",
    "pkcs": "PKCS标准",
    "x509": "X.509标准",
    "ocsp": "OCSP协议",
    "crl": "证书吊销列表",
    "crl distribution": "CRL分发点",
    "aia": "授权信息访问",
    "san": "主体备用名称",
    "cn": "通用名称",
    "ou": "组织单位",
    "o": "组织",
    "l": "地点",
    "st": "州/省",
    "c": "国家",
    "email": "电子邮件",
    "subject": "主题",
    "issuer": "颁发者",
    "serial": "序列号",
    "validity": "有效期",
    "not before": "生效时间",
    "not after": "过期时间",
    "fingerprint": "指纹",
    "thumbprint": "指纹",
    "chain": "链",
    "bundle": "包",
    "intermediate": "中间证书",
    "root ca": "根证书",
    "self signed": "自签名",
    "expired": "已过期",
    "revoked": "已吊销",
    "valid": "有效",
    "invalid": "无效",
    "trusted": "受信任",
    "untrusted": "不受信任",
    "secure": "安全",
    "insecure": "不安全",
    "vulnerability": "漏洞",
    "exploit": "漏洞利用",
    "patch": "补丁",
    "fix": "修复",
    "mitigation": "缓解",
    "workaround": "临时解决方案",
    "backdoor": "后门",
    "malware": "恶意软件",
    "virus": "病毒",
    "trojan": "木马",
    "worm": "蠕虫",
    "ransomware": "勒索软件",
    "spyware": "间谍软件",
    "adware": "广告软件",
    "rootkit": "rootkit",
    "keylogger": "键盘记录器",
    "botnet": "僵尸网络",
    "ddos": "分布式拒绝服务",
    "dos": "拒绝服务",
    "brute force": "暴力破解",
    "dictionary attack": "字典攻击",
    "rainbow table": "彩虹表",
    "salt": "盐值",
    "pepper": "胡椒值",
    "hash": "哈希",
    "bcrypt": "bcrypt",
    "scrypt": "scrypt",
    "argon2": "Argon2",
    "pbkdf2": "PBKDF2",
    "totp": "基于时间的一次性密码",
    "hotp": "基于计数器的一次性密码",
    "mfa": "多因素认证",
    "2fa": "双因素认证",
    "sms": "短信",
    "email": "电子邮件",
    "authenticator": "验证器",
    "biometric": "生物识别",
    "fingerprint": "指纹",
    "face id": "面容ID",
    "iris": "虹膜",
    "voice": "语音",
    "captcha": "验证码",
    "recaptcha": "reCAPTCHA",
    "hcaptcha": "hCaptcha",
    "turnstile": "Turnstile",
    "challenge": "挑战",
    "response": "响应",
    "token": "令牌",
    "access token": "访问令牌",
    "refresh token": "刷新令牌",
    "id token": "ID令牌",
    "bearer": "持有者",
    "basic": "基本认证",
    "digest": "摘要认证",
    "ntlm": "NTLM认证",
    "kerberos": "Kerberos认证",
    "saml": "SAML",
    "oidc": "OpenID Connect",
    "oauth2": "OAuth2",
    "authorization code": "授权码",
    "implicit": "隐式",
    "client credentials": "客户端凭证",
    "resource owner": "资源所有者",
    "device code": "设备码",
    "pkce": "PKCE",
    "code verifier": "代码验证器",
    "code challenge": "代码挑战",
    "redirect uri": "重定向URI",
    "scope": "作用域",
    "claim": "声明",
    "audience": "受众",
    "issuer": "颁发者",
    "subject": "主题",
    "expiry": "过期",
    "issued at": "签发时间",
    "not before": "生效时间",
    "jwt id": "JWT ID",
    "algorithm": "算法",
    "signature": "签名",
    "header": "头部",
    "payload": "负载",
    "base64": "Base64",
    "url safe": "URL安全",
    "padding": "填充",
    "header": "头部",
    "payload": "负载",
    "signature": "签名",
    "verify": "验证",
    "decode": "解码",
    "encode": "编码",
    "sign": "签名",
    "encrypt": "加密",
    "decrypt": "解密",
    "cipher": "密码",
    "block cipher": "分组密码",
    "stream cipher": "流密码",
    "mode": "模式",
    "ecb": "电子密码本",
    "cbc": "密码块链接",
    "cfb": "密码反馈",
    "ofb": "输出反馈",
    "ctr": "计数器",
    "gcm": "GCM",
    "ccm": "CCM",
    "chacha20": "ChaCha20",
    "poly1305": "Poly1305",
    "salsa20": "Salsa20",
    "xsalsa20": "XSalsa20",
    "xchacha20": "XChaCha20",
    "authenticated": "认证的",
    "unauthenticated": "未认证的",
    "associated": "关联的",
    "aad": "附加认证数据",
    "nonce": "随机数",
    "iv": "初始化向量",
    "key": "密钥",
    "key size": "密钥大小",
    "key length": "密钥长度",
    "key derivation": "密钥派生",
    "key exchange": "密钥交换",
    "diffie hellman": "Diffie-Hellman",
    "elliptic curve": "椭圆曲线",
    "ecdh": "ECDH",
    "ecdsa": "ECDSA",
    "ed25519": "Ed25519",
    "ed448": "Ed448",
    "x25519": "X25519",
    "x448": "X448",
    "curve25519": "Curve25519",
    "edwards": "爱德华兹",
    "montgomery": "蒙哥马利",
    "twisted": "扭曲",
    "birational": "双有理",
    "isomorphism": "同构",
    "homomorphism": "同态",
    "endomorphism": "自同态",
    "automorphism": "自同构",
    "isogeny": "同源",
    "kernel": "核",
    "image": "像",
    "cokernel": "余核",
    "coimage": "余像",
    "exact": "正合",
    "sequence": "序列",
    "short": "短",
    "long": "长",
    "split": "分裂",
    "extension": "扩张",
    "group": "群",
    "ring": "环",
    "field": "域",
    "module": "模",
    "vector space": "向量空间",
    "algebra": "代数",
    "coalgebra": "余代数",
    "bialgebra": "双代数",
    "hopf algebra": "Hopf代数",
    "lie algebra": "李代数",
    "clifford algebra": "Clifford代数",
    "exterior algebra": "外代数",
    "tensor algebra": "张量代数",
    "symmetric algebra": "对称代数",
    "universal enveloping": "泛包络",
    "quantum": "量子",
    "qubit": "量子比特",
    "qutrit": "量子三态",
    "qudit": "量子d态",
    "superposition": "叠加",
    "entanglement": "纠缠",
    "interference": "干涉",
    "measurement": "测量",
    "collapse": "坍缩",
    "decoherence": "退相干",
    "noise": "噪声",
    "error": "错误",
    "correction": "校正",
    "fault tolerant": "容错",
    "threshold": "阈值",
    "surface code": "表面码",
    "stabilizer": "稳定子",
    "syndrome": "症状",
    "decoder": "解码器",
    "encoder": "编码器",
    "logical": "逻辑",
    "physical": "物理",
    "virtual": "虚拟",
    "abstract": "抽象",
    "concrete": "具体",
    "interface": "接口",
    "implementation": "实现",
    "specification": "规范",
    "contract": "契约",
    "invariant": "不变量",
    "precondition": "前置条件",
    "postcondition": "后置条件",
    "assertion": "断言",
    "assumption": "假设",
    "guarantee": "保证",
    "property": "属性",
    "behavior": "行为",
    "semantics": "语义",
    "syntax": "语法",
    "grammar": "文法",
    "parser": "解析器",
    "lexer": "词法分析器",
    "tokenizer": "分词器",
    "scanner": "扫描器",
    "compiler": "编译器",
    "interpreter": "解释器",
    "transpiler": "转译器",
    "assembler": "汇编器",
    "linker": "链接器",
    "loader": "加载器",
    "preprocessor": "预处理器",
    "postprocessor": "后处理器",
    "optimizer": "优化器",
    "minifier": "压缩器",
    "uglifier": "混淆器",
    "beautifier": "美化器",
    "formatter": "格式化器",
    "linter": "检查器",
    "checker": "检查器",
    "validator": "验证器",
    "sanitizer": "清理器",
    "escaper": "转义器",
    "encoder": "编码器",
    "decoder": "解码器",
    "converter": "转换器",
    "transformer": "转换器",
    "adapter": "适配器",
    "wrapper": "包装器",
    "decorator": "装饰器",
    "mixin": "混入",
    "trait": "特征",
    "protocol": "协议",
    "abstract class": "抽象类",
    "concrete class": "具体类",
    "base class": "基类",
    "derived class": "派生类",
    "parent class": "父类",
    "child class": "子类",
    "superclass": "超类",
    "subclass": "子类",
    "instance": "实例",
    "object": "对象",
    "class": "类",
    "struct": "结构体",
    "enum": "枚举",
    "union": "联合体",
    "type": "类型",
    "typedef": "类型定义",
    "alias": "别名",
    "namespace": "命名空间",
    "package": "包",
    "module": "模块",
    "library": "库",
    "framework": "框架",
    "toolkit": "工具包",
    "sdk": "软件开发工具包",
    "api": "应用程序接口",
    "abi": "应用程序二进制接口",
    "abi stability": "ABI稳定性",
    "source compatibility": "源代码兼容性",
    "binary compatibility": "二进制兼容性",
    "backward compatible": "向后兼容",
    "forward compatible": "向前兼容",
    "breaking change": "破坏性变更",
    "deprecation": "弃用",
    "removal": "移除",
    "migration": "迁移",
    "upgrade": "升级",
    "downgrade": "降级",
    "rollback": "回滚",
    "revert": "还原",
    "hotfix": "热修复",
    "patch": "补丁",
    "minor": "次要",
    "major": "主要",
    "semver": "语义化版本",
    "version": "版本",
    "release": "发行版",
    "pre release": "预发布",
    "alpha": "阿尔法",
    "beta": "贝塔",
    "rc": "候选发布",
    "stable": "稳定",
    "latest": "最新",
    "lts": "长期支持",
    "maintenance": "维护",
    "end of life": "生命周期结束",
    "sunset": "日落",
    "deprecated": "已弃用",
    "obsolete": "过时",
    "legacy": "遗留",
    "modern": "现代",
    "current": "当前",
    "previous": "上一个",
    "next": "下一个",
    "experimental": "实验性",
    "stable": "稳定",
    "unstable": "不稳定",
    "nightly": "每夜构建",
    "canary": "金丝雀",
    "dev": "开发",
    "debug": "调试",
    "release": "发布",
    "production": "生产",
    "staging": "预发布",
    "testing": "测试",
    "development": "开发",
    "local": "本地",
    "remote": "远程",
    "cloud": "云",
    "on premise": "本地部署",
    "hybrid": "混合",
    "multi cloud": "多云",
    "edge": "边缘",
    "fog": "雾",
    "mist": "薄雾",
    "iot": "物联网",
    "embedded": "嵌入式",
    "realtime": "实时",
    "batch": "批处理",
    "streaming": "流处理",
    "online": "在线",
    "offline": "离线",
    "connected": "已连接",
    "disconnected": "已断开",
    "sync": "同步",
    "async": "异步",
    "blocking": "阻塞",
    "non blocking": "非阻塞",
    "concurrent": "并发",
    "parallel": "并行",
    "distributed": "分布式",
    "centralized": "集中式",
    "decentralized": "去中心化",
    "peer to peer": "点对点",
    "client server": "客户端-服务器",
    "request response": "请求-响应",
    "publish subscribe": "发布-订阅",
    "event driven": "事件驱动",
    "message driven": "消息驱动",
    "actor model": "Actor模型",
    "csp": "通信顺序进程",
    "goroutine": "协程",
    "coroutine": "协程",
    "fiber": "纤程",
    "green thread": "绿色线程",
    "native thread": "原生线程",
    "thread pool": "线程池",
    "worker": "工作者",
    "task": "任务",
    "job": "作业",
    "queue": "队列",
    "stack": "栈",
    "heap": "堆",
    "buffer": "缓冲区",
    "cache": "缓存",
    "pool": "池",
    "singleton": "单例",
    "factory": "工厂",
    "builder": "构建器",
    "prototype": "原型",
    "adapter": "适配器",
    "bridge": "桥接",
    "composite": "组合",
    "decorator": "装饰器",
    "facade": "外观",
    "flyweight": "享元",
    "proxy": "代理",
    "chain of responsibility": "责任链",
    "command": "命令",
    "interpreter": "解释器",
    "iterator": "迭代器",
    "mediator": "中介者",
    "memento": "备忘录",
    "observer": "观察者",
    "state": "状态",
    "strategy": "策略",
    "template method": "模板方法",
    "visitor": "访问者",
    "null object": "空对象",
    "dependency injection": "依赖注入",
    "inversion of control": "控制反转",
    "service locator": "服务定位器",
    "repository pattern": "仓储模式",
    "unit of work": "工作单元",
    "data mapper": "数据映射器",
    "active record": "活动记录",
    "table gateway": "表网关",
    "row data gateway": "行数据网关",
    "stored procedure": "存储过程",
    "view": "视图",
    "trigger": "触发器",
    "index": "索引",
    "constraint": "约束",
    "foreign key": "外键",
    "primary key": "主键",
    "unique key": "唯一键",
    "composite key": "复合键",
    "candidate key": "候选键",
    "surrogate key": "代理键",
    "natural key": "自然键",
    "normalization": "规范化",
    "denormalization": "反规范化",
    "first normal form": "第一范式",
    "second normal form": "第二范式",
    "third normal form": "第三范式",
    "boyce codd normal form": "BC范式",
    "fourth normal form": "第四范式",
    "fifth normal form": "第五范式",
    "domain key normal form": "域/键范式",
    "join": "连接",
    "inner join": "内连接",
    "outer join": "外连接",
    "left join": "左连接",
    "right join": "右连接",
    "full join": "全连接",
    "cross join": "交叉连接",
    "self join": "自连接",
    "natural join": "自然连接",
    "subquery": "子查询",
    "correlated subquery": "关联子查询",
    "common table expression": "公用表表达式",
    "window function": "窗口函数",
    "aggregate function": "聚合函数",
    "scalar function": "标量函数",
    "table valued function": "表值函数",
    "stored procedure": "存储过程",
    "trigger": "触发器",
    "event": "事件",
    "schedule": "调度",
    "job": "作业",
    "task": "任务",
    "batch": "批处理",
    "cursor": "游标",
    "transaction": "事务",
    "acid": "ACID",
    "atomicity": "原子性",
    "consistency": "一致性",
    "isolation": "隔离性",
    "durability": "持久性",
    "isolation level": "隔离级别",
    "read uncommitted": "读未提交",
    "read committed": "读已提交",
    "repeatable read": "可重复读",
    "serializable": "可串行化",
    "dirty read": "脏读",
    "non repeatable read": "不可重复读",
    "phantom read": "幻读",
    "lost update": "丢失更新",
    "locking": "锁定",
    "pessimistic": "悲观",
    "optimistic": "乐观",
    "mvcc": "多版本并发控制",
    "snapshot": "快照",
    "versioning": "版本控制",
    "timestamp": "时间戳",
    "sequence": "序列",
    "auto increment": "自增",
    "identity": "标识",
    "generated": "生成",
    "computed": "计算",
    "virtual": "虚拟",
    "stored": "存储",
    "materialized": "物化",
    "indexed": "已索引",
    "unindexed": "未索引",
    "clustered": "聚集",
    "non clustered": "非聚集",
    "b tree": "B树",
    "hash": "哈希",
    "bitmap": "位图",
    "gin": "GIN",
    "gist": "GiST",
    "sp gist": "SP-GiST",
    "brin": "BRIN",
    "full text": "全文",
    "tsvector": "tsvector",
    "tsquery": "tsquery",
    "tsrank": "tsrank",
    "tsheadline": "tsheadline",
    "tsexcerpt": "tsexcerpt",
    "tsparse": "tsparse",
    "ts_rewrite": "ts_rewrite",
    "ts_stat": "ts_stat",
    "ts_token_type": "ts_token_type",
    "ts_lexize": "ts_lexize",
    "ts_filter": "ts_filter",
    "ts_delete": "ts_delete",
    "ts_setweight": "ts_setweight",
    "ts_concat": "ts_concat",
    "ts_match_qv": "ts_match_qv",
    "ts_match_vq": "ts_match_vq",
    "ts_match_tt": "ts_match_tt",
    "ts_match_qq": "ts_match_qq",
    "ts_match_vv": "ts_match_vv",
    "ts_match_qt": "ts_match_qt",
    "ts_match_tq": "ts_match_tq",
    "ts_match_tv": "ts_match_tv",
    "ts_match_vt": "ts_match_vt",
}

# 预编译本地翻译正则（匹配完整单词，大小写不敏感）
_LOCAL_TRANSLATION_PATTERN = _re.compile(
    r'\b(' + '|'.join(_re.escape(k) for k in LOCAL_TRANSLATION_DICT.keys()) + r')\b',
    _re.IGNORECASE
)


def local_translate(text: str, target: str = "zh-CN") -> str:
    """使用本地词典翻译文本，仅支持英译中。"""
    if target not in ("zh-CN", "zh-TW", "zh"):
        return text
    source = str(text or "")
    if not source.strip():
        return source

    def _replace(match) -> str:
        key = match.group(0).lower()
        return LOCAL_TRANSLATION_DICT.get(key, match.group(0))

    return _LOCAL_TRANSLATION_PATTERN.sub(_replace, source)


# ---------------------------------------------------------------------------
# 腾讯云 TC3-HMAC-SHA256 签名
# ---------------------------------------------------------------------------

def tc3_authorization(
    secret_id: str,
    secret_key: str,
    host: str,
    service_name: str,
    action: str,
    version: str,
    region: str,
    payload: dict,
) -> tuple[str, str, str]:
    """计算腾讯云 TC3 签名。

    返回 (authorization 头, body 字符串, 签名时间戳)，调用方自行组装请求头。
    仅依赖标准库，行为与原 main.py 内联实现一致。
    """
    timestamp = int(_time.time())
    date = _datetime.datetime.fromtimestamp(timestamp, tz=_datetime.timezone.utc).strftime("%Y-%m-%d")
    body = _json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    hashed_payload = _hashlib.sha256(body.encode("utf-8")).hexdigest()
    canonical_headers = "content-type:application/json; charset=utf-8\nhost:" + host + "\n"
    signed_headers = "content-type;host"
    canonical_request = "\n".join(
        ("POST", "/", "", canonical_headers, signed_headers, hashed_payload)
    )
    credential_scope = f"{date}/{service_name}/tc3_request"
    string_to_sign = "\n".join(
        (
            "TC3-HMAC-SHA256",
            str(timestamp),
            credential_scope,
            _hashlib.sha256(canonical_request.encode("utf-8")).hexdigest(),
        )
    )
    secret_date = _hmac.new(
        ("TC3" + secret_key).encode("utf-8"),
        date.encode("utf-8"),
        _hashlib.sha256,
    ).digest()
    secret_service = _hmac.new(
        secret_date,
        service_name.encode("utf-8"),
        _hashlib.sha256,
    ).digest()
    secret_signing = _hmac.new(
        secret_service,
        b"tc3_request",
        _hashlib.sha256,
    ).digest()
    signature = _hmac.new(
        secret_signing,
        string_to_sign.encode("utf-8"),
        _hashlib.sha256,
    ).hexdigest()
    authorization = (
        "TC3-HMAC-SHA256 "
        f"Credential={secret_id}/{credential_scope}, "
        f"SignedHeaders={signed_headers}, Signature={signature}"
    )
    return authorization, body, str(timestamp)
